# Experiment parameters
DATA: 'neuroskin'
TASK: 'csr'  # 'osr'
LOSS: 'dag'  # 'ce' 'hice' 'hicon' 'dag' 'arpl'
DISENT: False
SAMPLER: 'hierarchical' # 'custom' 'random'
SEED: 2023
NUM_WORKERS: 1
NUM_FOLDS: 5